### ISSUE TITLE
Your code is not working for some reason. It is not updating anymore.

### ISSUE THREAD

**Issue by gp86041** [maxsommer/lametric-time-toggl#2]

**Comment by gp86041** [comment]
The app is not updating my toggl status, it is just showing generic 2:15 label.

**Comment by maxsommer** [comment]
Hi there ✌🏼 First off — Glad you're interested in the app.
I cannot really reproduce the situation you're experiencing but I have a hunch to what might be going on.
The app is working for me and the API required for the app is also available and online (https://lametric-time-toggl.herokuapp.com/api/v1).

Have you already set up a personal api token for your toggl.com? You can find it this way:
1. Go to toggl.com and sign in to your account
2. Click on your profile page link on the bottom left 
3. Click on 'Profile settings'
4. Scroll down to 'API Token'

Please let me know whether this worked for you.

**Comment by gp86041** [comment]
Thank you for the reply, it is working for me now. Maybe the issue is intermittent? Not sure what's happening here. Thank you making such a great app thought.

**Comment by maxsommer** [comment]
Thanks, I'll try and keep an eye on the issue :)
